// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomePageDocumentDataSlicesSlice =
  | VideoComponentSlice
  | TextBlocksSlice
  | FooterSlice
  | FaQSlice
  | SpeakerTakeawaySlice
  | StageFormatsSlice
  | WhatYouTakeAwaySlice
  | SpeakersOfBangaloreEditionSlice
  | PartnersSlice
  | AgendaSlice
  | WhyThisEventSlice
  | WhosInTheRoomSlice
  | SectorsRepresentedSlice
  | HeroSectionSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

/**
 * Content for Nav Modal documents
 */
interface NavModalDocumentData {
  /**
   * Logo field in *Nav Modal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_modal.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Item One Icon field in *Nav Modal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_modal.item_one_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  item_one_icon: prismic.ImageField<never>;

  /**
   * Icon One Text field in *Nav Modal*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_modal.icon_one_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  icon_one_text: prismic.RichTextField;

  /**
   * Item Two Icon field in *Nav Modal*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_modal.item_two_icon
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  item_two_icon: prismic.ImageField<never>;

  /**
   * Item Two Rich Text field in *Nav Modal*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_modal.item_two_rich_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  item_two_rich_text: prismic.RichTextField;

  /**
   * Item Two Text field in *Nav Modal*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_modal.item_two_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  item_two_text: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * CTA Link field in *Nav Modal*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_modal.cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button Text field in *Nav Modal*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: nav_modal.button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Nav Modal document from Prismic
 *
 * - **API ID**: `nav_modal`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavModalDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavModalDocumentData>,
    "nav_modal",
    Lang
  >;

/**
 * Content for Page Modals documents
 */
interface PageModalsDocumentData {
  /**
   * Logo field in *Page Modals*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page_modals.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Heading field in *Page Modals*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_modals.heading
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *Page Modals*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_modals.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * CTA Link field in *Page Modals*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: page_modals.cta_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button text field in *Page Modals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page_modals.button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Page Modals document from Prismic
 *
 * - **API ID**: `page_modals`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageModalsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PageModalsDocumentData>,
    "page_modals",
    Lang
  >;

type PreviewDocumentDataSlicesSlice =
  | VideoComponentSlice
  | WhosInTheRoomSlice
  | WhatYouTakeAwaySlice
  | WhyThisEventSlice
  | TextBlocksSlice
  | StageFormatsSlice
  | SpeakersOfBangaloreEditionSlice
  | SpeakerTakeawaySlice
  | SectorsRepresentedSlice
  | FaQSlice
  | PartnersSlice
  | HeroSectionSlice
  | FooterSlice
  | AgendaSlice;

/**
 * Content for preview documents
 */
interface PreviewDocumentData {
  /**
   * Slice Zone field in *preview*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: preview.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PreviewDocumentDataSlicesSlice>; /**
   * Meta Title field in *preview*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: preview.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *preview*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: preview.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *preview*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: preview.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * preview document from Prismic
 *
 * - **API ID**: `preview`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PreviewDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PreviewDocumentData>,
    "preview",
    Lang
  >;

export type AllDocumentTypes =
  | HomePageDocument
  | NavModalDocument
  | PageModalsDocument
  | PreviewDocument;

/**
 * Item in *Agenda → Default → Primary → Blocks*
 */
export interface AgendaSliceDefaultPrimaryBlocksItem {
  /**
   * Time field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  time: prismic.KeyTextField;

  /**
   * Title field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Title or Images field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Add icons /img
   * - **API ID Path**: agenda.default.primary.blocks[].title_or_images
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title_or_images: prismic.RichTextField;

  /**
   * Short description field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].short_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_description: prismic.RichTextField;

  /**
   * Speaker One field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  speaker: prismic.ImageField<never>;

  /**
   * Speaker One Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  speaker_name: prismic.KeyTextField;

  /**
   * LinkedInOne field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Speaker one's LinkedIn
   * - **API ID Path**: agenda.default.primary.blocks[].linkedinone
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedinone: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Speaker two field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_two
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  speaker_two: prismic.ImageField<never>;

  /**
   * Speaker two name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_two_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  speaker_two_name: prismic.KeyTextField;

  /**
   * LinkedInTwo field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Speaker two's LinkedIn
   * - **API ID Path**: agenda.default.primary.blocks[].linkedintwo
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedintwo: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Speaker Three Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_three_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  speaker_three_image: prismic.ImageField<never>;

  /**
   * Speaker Three Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_three_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  speaker_three_name: prismic.RichTextField;

  /**
   * Speaker Three LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_three_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  speaker_three_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Speaker Four Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_four_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  speaker_four_image: prismic.ImageField<never>;

  /**
   * Speaker Four Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_four_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  speaker_four_name: prismic.RichTextField;

  /**
   * Speaker Four LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_four_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  speaker_four_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Speaker Five Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_five_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  speaker_five_image: prismic.ImageField<never>;

  /**
   * Speaker Five Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_five_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  speaker_five_name: prismic.RichTextField;

  /**
   * Speaker Five LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_five_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  speaker_five_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Moderator One Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_one_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  moderator_one_image: prismic.ImageField<never>;

  /**
   * Moderator One Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_one_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  moderator_one_name: prismic.RichTextField;

  /**
   * Moderator One LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_one_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  moderator_one_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Moderator Two Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_two_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  moderator_two_image: prismic.ImageField<never>;

  /**
   * Moderator Two Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_two_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  moderator_two_name: prismic.RichTextField;

  /**
   * Moderator Two LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_two_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  moderator_two_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Moderator Three Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_three_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  moderator_three_image: prismic.ImageField<never>;

  /**
   * Moderator Three Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_three_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  moderator_three_name: prismic.RichTextField;

  /**
   * Moderator Three LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_three_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  moderator_three_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Moderator Four Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_four_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  moderator_four_image: prismic.ImageField<never>;

  /**
   * Moderator Four Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_four_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  moderator_four_name: prismic.RichTextField;

  /**
   * Moderator Four LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].moderator_four_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  moderator_four_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Facilitator One Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_one_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  facilitator_one_image: prismic.ImageField<never>;

  /**
   * Facilitator One Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_one_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  facilitator_one_name: prismic.RichTextField;

  /**
   * Facilitator One LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_one_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  facilitator_one_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Facilitator Two Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_two_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  facilitator_two_image: prismic.ImageField<never>;

  /**
   * Facilitator Two Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_two_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  facilitator_two_name: prismic.RichTextField;

  /**
   * Facilitator Two LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_two_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  facilitator_two_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Facilitator Three Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_three_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  facilitator_three_image: prismic.ImageField<never>;

  /**
   * Facilitator Three Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_three_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  facilitator_three_name: prismic.RichTextField;

  /**
   * Facilitator Three LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_three_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  facilitator_three_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Facilitator Four Image field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_four_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  facilitator_four_image: prismic.ImageField<never>;

  /**
   * Facilitator Four Name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_four_name
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  facilitator_four_name: prismic.RichTextField;

  /**
   * Facilitator Four LinkedIn field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].facilitator_four_linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  facilitator_four_linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Agenda → Default → Primary*
 */
export interface AgendaSliceDefaultPrimary {
  /**
   * Heading field in *Agenda → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Blocks field in *Agenda → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  blocks: prismic.GroupField<Simplify<AgendaSliceDefaultPrimaryBlocksItem>>;

  /**
   * Show Slice field in *Agenda → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: agenda.default.primary.show_slice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_slice: prismic.BooleanField;
}

/**
 * Default variation for Agenda Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AgendaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AgendaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Agenda*
 */
type AgendaSliceVariation = AgendaSliceDefault;

/**
 * Agenda Shared Slice
 *
 * - **API ID**: `agenda`
 * - **Description**: Agenda
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AgendaSlice = prismic.SharedSlice<"agenda", AgendaSliceVariation>;

/**
 * Item in *FaQ → Default → Primary → FAQ*
 */
export interface FaQSliceDefaultPrimaryFaqItem {
  /**
   * Title field in *FaQ → Default → Primary → FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fa_q.default.primary.faq[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *FaQ → Default → Primary → FAQ*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fa_q.default.primary.faq[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *FaQ → Default → Primary*
 */
export interface FaQSliceDefaultPrimary {
  /**
   * Show Slice field in *FaQ → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: fa_q.default.primary.show_slice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_slice: prismic.BooleanField;

  /**
   * Heading field in *FaQ → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: fa_q.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * FAQ field in *FaQ → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: fa_q.default.primary.faq[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  faq: prismic.GroupField<Simplify<FaQSliceDefaultPrimaryFaqItem>>;
}

/**
 * Default variation for FaQ Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaQSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaQSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *FaQ*
 */
type FaQSliceVariation = FaQSliceDefault;

/**
 * FaQ Shared Slice
 *
 * - **API ID**: `fa_q`
 * - **Description**: FaQ
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FaQSlice = prismic.SharedSlice<"fa_q", FaQSliceVariation>;

/**
 * Primary content in *Footer → Default → Primary*
 */
export interface FooterSliceDefaultPrimary {
  /**
   * Show Slice field in *Footer → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: footer.default.primary.show_slice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_slice: prismic.BooleanField;

  /**
   * Logos field in *Footer → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.logos
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logos: prismic.ImageField<never>;

  /**
   * Date Text field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.date_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date_text: prismic.KeyTextField;

  /**
   * Location field in *Footer → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.location
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  location: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Time Text field in *Footer → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.time_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  time_text: prismic.KeyTextField;

  /**
   * Description with link field in *Footer → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: footer.default.primary.description_with_link
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description_with_link: prismic.RichTextField;
}

/**
 * Default variation for Footer Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FooterSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Footer*
 */
type FooterSliceVariation = FooterSliceDefault;

/**
 * Footer Shared Slice
 *
 * - **API ID**: `footer`
 * - **Description**: Footer
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FooterSlice = prismic.SharedSlice<"footer", FooterSliceVariation>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Heading field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Date text field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.date_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  date_text: prismic.KeyTextField;

  /**
   * Date field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.date
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  date: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Time field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  time: prismic.KeyTextField;

  /**
   * Location field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.location
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  location: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Image or Video field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.image_or_video
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image_or_video: prismic.ImageField<never>;

  /**
   * Video Toggle field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: hero_section.default.primary.video_toggle
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  video_toggle: prismic.BooleanField;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Item in *Participants → Default → Primary → Companies*
 */
export interface PartnersSliceDefaultPrimaryCompaniesItem {
  /**
   * Logo field in *Participants → Default → Primary → Companies*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.companies[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Link field in *Participants → Default → Primary → Companies*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.companies[].link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *Participants → Default → Primary*
 */
export interface PartnersSliceDefaultPrimary {
  /**
   * Show Slice field in *Participants → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: partners.default.primary.show_slice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_slice: prismic.BooleanField;

  /**
   * Companies field in *Participants → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.companies[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  companies: prismic.GroupField<
    Simplify<PartnersSliceDefaultPrimaryCompaniesItem>
  >;
}

/**
 * Default variation for Participants Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Participants*
 */
type PartnersSliceVariation = PartnersSliceDefault;

/**
 * Participants Shared Slice
 *
 * - **API ID**: `partners`
 * - **Description**: Partners
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnersSlice = prismic.SharedSlice<
  "partners",
  PartnersSliceVariation
>;

/**
 * Item in *SectorsRepresented → Default → Primary → Marquee*
 */
export interface SectorsRepresentedSliceDefaultPrimaryMarqueeItem {
  /**
   * Partners field in *SectorsRepresented → Default → Primary → Marquee*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sectors_represented.default.primary.marquee[].partners
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  partners: prismic.KeyTextField;
}

/**
 * Primary content in *SectorsRepresented → Default → Primary*
 */
export interface SectorsRepresentedSliceDefaultPrimary {
  /**
   * Show Slice field in *SectorsRepresented → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: sectors_represented.default.primary.show_slice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_slice: prismic.BooleanField;

  /**
   * Heading field in *SectorsRepresented → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sectors_represented.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Marquee field in *SectorsRepresented → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sectors_represented.default.primary.marquee[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  marquee: prismic.GroupField<
    Simplify<SectorsRepresentedSliceDefaultPrimaryMarqueeItem>
  >;
}

/**
 * Default variation for SectorsRepresented Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectorsRepresentedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectorsRepresentedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectorsRepresented*
 */
type SectorsRepresentedSliceVariation = SectorsRepresentedSliceDefault;

/**
 * SectorsRepresented Shared Slice
 *
 * - **API ID**: `sectors_represented`
 * - **Description**: SectorsRepresented
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectorsRepresentedSlice = prismic.SharedSlice<
  "sectors_represented",
  SectorsRepresentedSliceVariation
>;

/**
 * Item in *SpeakerTakeaway → Default → Primary → Blocks*
 */
export interface SpeakerTakeawaySliceDefaultPrimaryBlocksItem {
  /**
   * icon field in *SpeakerTakeaway → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker_takeaway.default.primary.blocks[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Icon Shadow field in *SpeakerTakeaway → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker_takeaway.default.primary.blocks[].icon_shadow
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon_shadow: prismic.ImageField<never>;

  /**
   * Heading field in *SpeakerTakeaway → Default → Primary → Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker_takeaway.default.primary.blocks[].heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * description field in *SpeakerTakeaway → Default → Primary → Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker_takeaway.default.primary.blocks[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *SpeakerTakeaway → Default → Primary*
 */
export interface SpeakerTakeawaySliceDefaultPrimary {
  /**
   * Show Slice field in *SpeakerTakeaway → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: speaker_takeaway.default.primary.show_slice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_slice: prismic.BooleanField;

  /**
   * Heading field in *SpeakerTakeaway → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker_takeaway.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Blocks field in *SpeakerTakeaway → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: speaker_takeaway.default.primary.blocks[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  blocks: prismic.GroupField<
    Simplify<SpeakerTakeawaySliceDefaultPrimaryBlocksItem>
  >;
}

/**
 * Default variation for SpeakerTakeaway Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpeakerTakeawaySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SpeakerTakeawaySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SpeakerTakeaway*
 */
type SpeakerTakeawaySliceVariation = SpeakerTakeawaySliceDefault;

/**
 * SpeakerTakeaway Shared Slice
 *
 * - **API ID**: `speaker_takeaway`
 * - **Description**: SpeakerTakeaway
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpeakerTakeawaySlice = prismic.SharedSlice<
  "speaker_takeaway",
  SpeakerTakeawaySliceVariation
>;

/**
 * Item in *SpeakersOfBangaloreEdition → Default → Primary → Speaker*
 */
export interface SpeakersOfBangaloreEditionSliceDefaultPrimarySpeakerItem {
  /**
   * Speaker Image field in *SpeakersOfBangaloreEdition → Default → Primary → Speaker*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.speaker[].speaker_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  speaker_image: prismic.ImageField<never>;

  /**
   * Name field in *SpeakersOfBangaloreEdition → Default → Primary → Speaker*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.speaker[].name_rich
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name_rich: prismic.RichTextField;

  /**
   * Role field in *SpeakersOfBangaloreEdition → Default → Primary → Speaker*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.speaker[].role_rich
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  role_rich: prismic.RichTextField;

  /**
   * LinkedIn field in *SpeakersOfBangaloreEdition → Default → Primary → Speaker*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.speaker[].linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Item in *SpeakersOfBangaloreEdition → secondaryVar → Primary → Speaker*
 */
export interface SpeakersOfBangaloreEditionSliceSecondaryVarPrimarySpeakerItem {
  /**
   * Speaker Image field in *SpeakersOfBangaloreEdition → secondaryVar → Primary → Speaker*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.secondaryVar.primary.speaker[].speaker_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  speaker_image: prismic.ImageField<never>;

  /**
   * Name field in *SpeakersOfBangaloreEdition → secondaryVar → Primary → Speaker*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.secondaryVar.primary.speaker[].name_rich_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  name_rich_text: prismic.RichTextField;

  /**
   * Role field in *SpeakersOfBangaloreEdition → secondaryVar → Primary → Speaker*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.secondaryVar.primary.speaker[].role_rich_text
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  role_rich_text: prismic.RichTextField;

  /**
   * LinkedIn field in *SpeakersOfBangaloreEdition → secondaryVar → Primary → Speaker*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.secondaryVar.primary.speaker[].linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *SpeakersOfBangaloreEdition → Default → Primary*
 */
export interface SpeakersOfBangaloreEditionSliceDefaultPrimary {
  /**
   * Heading field in *SpeakersOfBangaloreEdition → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Speaker field in *SpeakersOfBangaloreEdition → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.speaker[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  speaker: prismic.GroupField<
    Simplify<SpeakersOfBangaloreEditionSliceDefaultPrimarySpeakerItem>
  >;
}

/**
 * Default variation for SpeakersOfBangaloreEdition Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpeakersOfBangaloreEditionSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<SpeakersOfBangaloreEditionSliceDefaultPrimary>,
    never
  >;

/**
 * Primary content in *SpeakersOfBangaloreEdition → secondaryVar → Primary*
 */
export interface SpeakersOfBangaloreEditionSliceSecondaryVarPrimary {
  /**
   * Show Slice field in *SpeakersOfBangaloreEdition → secondaryVar → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: speakers_of_bangalore_edition.secondaryVar.primary.show_slice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_slice: prismic.BooleanField;

  /**
   * Heading field in *SpeakersOfBangaloreEdition → secondaryVar → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.secondaryVar.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Speaker field in *SpeakersOfBangaloreEdition → secondaryVar → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.secondaryVar.primary.speaker[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  speaker: prismic.GroupField<
    Simplify<SpeakersOfBangaloreEditionSliceSecondaryVarPrimarySpeakerItem>
  >;
}

/**
 * secondaryVar variation for SpeakersOfBangaloreEdition Slice
 *
 * - **API ID**: `secondaryVar`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpeakersOfBangaloreEditionSliceSecondaryVar =
  prismic.SharedSliceVariation<
    "secondaryVar",
    Simplify<SpeakersOfBangaloreEditionSliceSecondaryVarPrimary>,
    never
  >;

/**
 * Slice variation for *SpeakersOfBangaloreEdition*
 */
type SpeakersOfBangaloreEditionSliceVariation =
  | SpeakersOfBangaloreEditionSliceDefault
  | SpeakersOfBangaloreEditionSliceSecondaryVar;

/**
 * SpeakersOfBangaloreEdition Shared Slice
 *
 * - **API ID**: `speakers_of_bangalore_edition`
 * - **Description**: SpeakersOfBangaloreEdition
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpeakersOfBangaloreEditionSlice = prismic.SharedSlice<
  "speakers_of_bangalore_edition",
  SpeakersOfBangaloreEditionSliceVariation
>;

/**
 * Item in *StageFormats → Default → Primary → Blocks*
 */
export interface StageFormatsSliceDefaultPrimaryBlocksItem {
  /**
   * Icon field in *StageFormats → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: stage_formats.default.primary.blocks[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Red block text field in *StageFormats → Default → Primary → Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stage_formats.default.primary.blocks[].red_block_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  red_block_text: prismic.KeyTextField;

  /**
   * Title field in *StageFormats → Default → Primary → Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stage_formats.default.primary.blocks[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *StageFormats → Default → Primary → Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stage_formats.default.primary.blocks[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;
}

/**
 * Primary content in *StageFormats → Default → Primary*
 */
export interface StageFormatsSliceDefaultPrimary {
  /**
   * Show Slice field in *StageFormats → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: stage_formats.default.primary.show_slice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_slice: prismic.BooleanField;

  /**
   * Stage format field in *StageFormats → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stage_formats.default.primary.stage_format
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stage_format: prismic.KeyTextField;

  /**
   * Heading field in *StageFormats → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stage_formats.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Short description field in *StageFormats → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: stage_formats.default.primary.short_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_description: prismic.RichTextField;

  /**
   * Blocks field in *StageFormats → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: stage_formats.default.primary.blocks[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  blocks: prismic.GroupField<
    Simplify<StageFormatsSliceDefaultPrimaryBlocksItem>
  >;
}

/**
 * Default variation for StageFormats Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StageFormatsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<StageFormatsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *StageFormats*
 */
type StageFormatsSliceVariation = StageFormatsSliceDefault;

/**
 * StageFormats Shared Slice
 *
 * - **API ID**: `stage_formats`
 * - **Description**: StageFormats
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type StageFormatsSlice = prismic.SharedSlice<
  "stage_formats",
  StageFormatsSliceVariation
>;

/**
 * Primary content in *TextBlocks → Text on Left → Primary*
 */
export interface TextBlocksSliceDefaultPrimary {
  /**
   * Heading field in *TextBlocks → Text on Left → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_blocks.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * showSlice field in *TextBlocks → Text on Left → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text_blocks.default.primary.showslice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showslice: prismic.BooleanField;
}

/**
 * Text on Left variation for TextBlocks Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlocksSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextBlocksSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TextBlocks → Text on Middle → Primary*
 */
export interface TextBlocksSliceTextOnMiddlePrimary {
  /**
   * Heading field in *TextBlocks → Text on Middle → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_blocks.textOnMiddle.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * showSlice field in *TextBlocks → Text on Middle → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text_blocks.textOnMiddle.primary.showslice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showslice: prismic.BooleanField;
}

/**
 * Text on Middle variation for TextBlocks Slice
 *
 * - **API ID**: `textOnMiddle`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlocksSliceTextOnMiddle = prismic.SharedSliceVariation<
  "textOnMiddle",
  Simplify<TextBlocksSliceTextOnMiddlePrimary>,
  never
>;

/**
 * Primary content in *TextBlocks → Heading and Description → Primary*
 */
export interface TextBlocksSliceHeadingAndDescriptionPrimary {
  /**
   * Heading field in *TextBlocks → Heading and Description → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_blocks.headingAndDescription.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *TextBlocks → Heading and Description → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_blocks.headingAndDescription.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * showSlice field in *TextBlocks → Heading and Description → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: text_blocks.headingAndDescription.primary.showslice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  showslice: prismic.BooleanField;
}

/**
 * Heading and Description variation for TextBlocks Slice
 *
 * - **API ID**: `headingAndDescription`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlocksSliceHeadingAndDescription = prismic.SharedSliceVariation<
  "headingAndDescription",
  Simplify<TextBlocksSliceHeadingAndDescriptionPrimary>,
  never
>;

/**
 * Slice variation for *TextBlocks*
 */
type TextBlocksSliceVariation =
  | TextBlocksSliceDefault
  | TextBlocksSliceTextOnMiddle
  | TextBlocksSliceHeadingAndDescription;

/**
 * TextBlocks Shared Slice
 *
 * - **API ID**: `text_blocks`
 * - **Description**: TextBlocks
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TextBlocksSlice = prismic.SharedSlice<
  "text_blocks",
  TextBlocksSliceVariation
>;

/**
 * Primary content in *VideoComponent → Default → Primary*
 */
export interface VideoComponentSliceDefaultPrimary {
  /**
   * Show Slice field in *VideoComponent → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: video_component.default.primary.show_slice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_slice: prismic.BooleanField;

  /**
   * Video link field in *VideoComponent → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: video_component.default.primary.video_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  video_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Link or Default field in *VideoComponent → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: video_component.default.primary.link_or_default
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  link_or_default: prismic.BooleanField;
}

/**
 * Default variation for VideoComponent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoComponentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoComponentSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VideoComponent*
 */
type VideoComponentSliceVariation = VideoComponentSliceDefault;

/**
 * VideoComponent Shared Slice
 *
 * - **API ID**: `video_component`
 * - **Description**: VideoComponent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoComponentSlice = prismic.SharedSlice<
  "video_component",
  VideoComponentSliceVariation
>;

/**
 * Item in *WhatYouTakeAway → Default → Primary → Blocks*
 */
export interface WhatYouTakeAwaySliceDefaultPrimaryBlocksItem {
  /**
   * Icon field in *WhatYouTakeAway → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: what_you_take_away.default.primary.blocks[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Title field in *WhatYouTakeAway → Default → Primary → Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_you_take_away.default.primary.blocks[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Short description field in *WhatYouTakeAway → Default → Primary → Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_you_take_away.default.primary.blocks[].short_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  short_description: prismic.KeyTextField;
}

/**
 * Primary content in *WhatYouTakeAway → Default → Primary*
 */
export interface WhatYouTakeAwaySliceDefaultPrimary {
  /**
   * Heading field in *WhatYouTakeAway → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_you_take_away.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Blocks field in *WhatYouTakeAway → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: what_you_take_away.default.primary.blocks[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  blocks: prismic.GroupField<
    Simplify<WhatYouTakeAwaySliceDefaultPrimaryBlocksItem>
  >;
}

/**
 * Default variation for WhatYouTakeAway Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhatYouTakeAwaySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhatYouTakeAwaySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhatYouTakeAway*
 */
type WhatYouTakeAwaySliceVariation = WhatYouTakeAwaySliceDefault;

/**
 * WhatYouTakeAway Shared Slice
 *
 * - **API ID**: `what_you_take_away`
 * - **Description**: WhatYouTakeAway
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhatYouTakeAwaySlice = prismic.SharedSlice<
  "what_you_take_away",
  WhatYouTakeAwaySliceVariation
>;

/**
 * Item in *WhosInTheRoom → Default → Primary → Info group*
 */
export interface WhosInTheRoomSliceDefaultPrimaryInfoGroupItem {
  /**
   * Info field in *WhosInTheRoom → Default → Primary → Info group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whos_in_the_room.default.primary.info_group[].info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  info: prismic.KeyTextField;
}

/**
 * Item in *WhosInTheRoom → withInfinity → Primary → Info group*
 */
export interface WhosInTheRoomSliceWithInfinityPrimaryInfoGroupItem {
  /**
   * Info field in *WhosInTheRoom → withInfinity → Primary → Info group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whos_in_the_room.withInfinity.primary.info_group[].info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  info: prismic.KeyTextField;
}

/**
 * Primary content in *WhosInTheRoom → Default → Primary*
 */
export interface WhosInTheRoomSliceDefaultPrimary {
  /**
   * Show Slice field in *WhosInTheRoom → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: whos_in_the_room.default.primary.show_slice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_slice: prismic.BooleanField;

  /**
   * Heading field in *WhosInTheRoom → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whos_in_the_room.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Info group field in *WhosInTheRoom → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: whos_in_the_room.default.primary.info_group[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  info_group: prismic.GroupField<
    Simplify<WhosInTheRoomSliceDefaultPrimaryInfoGroupItem>
  >;
}

/**
 * Default variation for WhosInTheRoom Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhosInTheRoomSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhosInTheRoomSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *WhosInTheRoom → withInfinity → Primary*
 */
export interface WhosInTheRoomSliceWithInfinityPrimary {
  /**
   * Heading field in *WhosInTheRoom → withInfinity → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whos_in_the_room.withInfinity.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Info group field in *WhosInTheRoom → withInfinity → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: whos_in_the_room.withInfinity.primary.info_group[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  info_group: prismic.GroupField<
    Simplify<WhosInTheRoomSliceWithInfinityPrimaryInfoGroupItem>
  >;

  /**
   * Show Slice field in *WhosInTheRoom → withInfinity → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: whos_in_the_room.withInfinity.primary.show_slice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_slice: prismic.BooleanField;
}

/**
 * withInfinity variation for WhosInTheRoom Slice
 *
 * - **API ID**: `withInfinity`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhosInTheRoomSliceWithInfinity = prismic.SharedSliceVariation<
  "withInfinity",
  Simplify<WhosInTheRoomSliceWithInfinityPrimary>,
  never
>;

/**
 * Slice variation for *WhosInTheRoom*
 */
type WhosInTheRoomSliceVariation =
  | WhosInTheRoomSliceDefault
  | WhosInTheRoomSliceWithInfinity;

/**
 * WhosInTheRoom Shared Slice
 *
 * - **API ID**: `whos_in_the_room`
 * - **Description**: WhosInTheRoom
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhosInTheRoomSlice = prismic.SharedSlice<
  "whos_in_the_room",
  WhosInTheRoomSliceVariation
>;

/**
 * Item in *WhyThisEvent → Default → Primary → Event Features*
 */
export interface WhyThisEventSliceDefaultPrimaryEventFeaturesItem {
  /**
   * Heading field in *WhyThisEvent → Default → Primary → Event Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_this_event.default.primary.event_features[].heading
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  heading: prismic.KeyTextField;

  /**
   * description field in *WhyThisEvent → Default → Primary → Event Features*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_this_event.default.primary.event_features[].description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  description: prismic.KeyTextField;

  /**
   * Icon field in *WhyThisEvent → Default → Primary → Event Features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: why_this_event.default.primary.event_features[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Icon Shadow field in *WhyThisEvent → Default → Primary → Event Features*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: why_this_event.default.primary.event_features[].icon_shadow
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon_shadow: prismic.ImageField<never>;
}

/**
 * Primary content in *WhyThisEvent → Default → Primary*
 */
export interface WhyThisEventSliceDefaultPrimary {
  /**
   * Show Slice field in *WhyThisEvent → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: why_this_event.default.primary.show_slice
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  show_slice: prismic.BooleanField;

  /**
   * Heading field in *WhyThisEvent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_this_event.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Event Features field in *WhyThisEvent → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: why_this_event.default.primary.event_features[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  event_features: prismic.GroupField<
    Simplify<WhyThisEventSliceDefaultPrimaryEventFeaturesItem>
  >;
}

/**
 * Default variation for WhyThisEvent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhyThisEventSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhyThisEventSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhyThisEvent*
 */
type WhyThisEventSliceVariation = WhyThisEventSliceDefault;

/**
 * WhyThisEvent Shared Slice
 *
 * - **API ID**: `why_this_event`
 * - **Description**: WhyThisEvent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhyThisEventSlice = prismic.SharedSlice<
  "why_this_event",
  WhyThisEventSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      NavModalDocument,
      NavModalDocumentData,
      PageModalsDocument,
      PageModalsDocumentData,
      PreviewDocument,
      PreviewDocumentData,
      PreviewDocumentDataSlicesSlice,
      AllDocumentTypes,
      AgendaSlice,
      AgendaSliceDefaultPrimaryBlocksItem,
      AgendaSliceDefaultPrimary,
      AgendaSliceVariation,
      AgendaSliceDefault,
      FaQSlice,
      FaQSliceDefaultPrimaryFaqItem,
      FaQSliceDefaultPrimary,
      FaQSliceVariation,
      FaQSliceDefault,
      FooterSlice,
      FooterSliceDefaultPrimary,
      FooterSliceVariation,
      FooterSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      PartnersSlice,
      PartnersSliceDefaultPrimaryCompaniesItem,
      PartnersSliceDefaultPrimary,
      PartnersSliceVariation,
      PartnersSliceDefault,
      SectorsRepresentedSlice,
      SectorsRepresentedSliceDefaultPrimaryMarqueeItem,
      SectorsRepresentedSliceDefaultPrimary,
      SectorsRepresentedSliceVariation,
      SectorsRepresentedSliceDefault,
      SpeakerTakeawaySlice,
      SpeakerTakeawaySliceDefaultPrimaryBlocksItem,
      SpeakerTakeawaySliceDefaultPrimary,
      SpeakerTakeawaySliceVariation,
      SpeakerTakeawaySliceDefault,
      SpeakersOfBangaloreEditionSlice,
      SpeakersOfBangaloreEditionSliceDefaultPrimarySpeakerItem,
      SpeakersOfBangaloreEditionSliceDefaultPrimary,
      SpeakersOfBangaloreEditionSliceSecondaryVarPrimarySpeakerItem,
      SpeakersOfBangaloreEditionSliceSecondaryVarPrimary,
      SpeakersOfBangaloreEditionSliceVariation,
      SpeakersOfBangaloreEditionSliceDefault,
      SpeakersOfBangaloreEditionSliceSecondaryVar,
      StageFormatsSlice,
      StageFormatsSliceDefaultPrimaryBlocksItem,
      StageFormatsSliceDefaultPrimary,
      StageFormatsSliceVariation,
      StageFormatsSliceDefault,
      TextBlocksSlice,
      TextBlocksSliceDefaultPrimary,
      TextBlocksSliceTextOnMiddlePrimary,
      TextBlocksSliceHeadingAndDescriptionPrimary,
      TextBlocksSliceVariation,
      TextBlocksSliceDefault,
      TextBlocksSliceTextOnMiddle,
      TextBlocksSliceHeadingAndDescription,
      VideoComponentSlice,
      VideoComponentSliceDefaultPrimary,
      VideoComponentSliceVariation,
      VideoComponentSliceDefault,
      WhatYouTakeAwaySlice,
      WhatYouTakeAwaySliceDefaultPrimaryBlocksItem,
      WhatYouTakeAwaySliceDefaultPrimary,
      WhatYouTakeAwaySliceVariation,
      WhatYouTakeAwaySliceDefault,
      WhosInTheRoomSlice,
      WhosInTheRoomSliceDefaultPrimaryInfoGroupItem,
      WhosInTheRoomSliceDefaultPrimary,
      WhosInTheRoomSliceWithInfinityPrimaryInfoGroupItem,
      WhosInTheRoomSliceWithInfinityPrimary,
      WhosInTheRoomSliceVariation,
      WhosInTheRoomSliceDefault,
      WhosInTheRoomSliceWithInfinity,
      WhyThisEventSlice,
      WhyThisEventSliceDefaultPrimaryEventFeaturesItem,
      WhyThisEventSliceDefaultPrimary,
      WhyThisEventSliceVariation,
      WhyThisEventSliceDefault,
    };
  }
}
