// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomePageDocumentDataSlicesSlice =
  | WhatYouTakeAwaySlice
  | SpeakersOfBangaloreEditionSlice
  | PartnersSlice
  | AgendaSlice
  | WhyThisEventSlice
  | WhosInTheRoomSlice
  | SectorsRepresentedSlice
  | HeroSectionSlice
  | FormSlice;

/**
 * Content for Home Page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *Home Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Home Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

export type AllDocumentTypes = HomePageDocument;

/**
 * Item in *Agenda → Default → Primary → Blocks*
 */
export interface AgendaSliceDefaultPrimaryBlocksItem {
  /**
   * Time field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  time: prismic.KeyTextField;

  /**
   * Title field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * Short description field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].short_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  short_description: prismic.RichTextField;

  /**
   * Speaker field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  speaker: prismic.ImageField<never>;

  /**
   * Speaker name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  speaker_name: prismic.KeyTextField;

  /**
   * Speaker two field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_two
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  speaker_two: prismic.ImageField<never>;

  /**
   * Speaker two name field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].speaker_two_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  speaker_two_name: prismic.KeyTextField;

  /**
   * Icon field in *Agenda → Default → Primary → Blocks*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Primary content in *Agenda → Default → Primary*
 */
export interface AgendaSliceDefaultPrimary {
  /**
   * Heading field in *Agenda → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Blocks field in *Agenda → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: agenda.default.primary.blocks[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  blocks: prismic.GroupField<Simplify<AgendaSliceDefaultPrimaryBlocksItem>>;
}

/**
 * Default variation for Agenda Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AgendaSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AgendaSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Agenda*
 */
type AgendaSliceVariation = AgendaSliceDefault;

/**
 * Agenda Shared Slice
 *
 * - **API ID**: `agenda`
 * - **Description**: Agenda
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AgendaSlice = prismic.SharedSlice<"agenda", AgendaSliceVariation>;

/**
 * Primary content in *Form → Default → Primary*
 */
export interface FormSliceDefaultPrimary {
  /**
   * Heading field in *Form → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Image field in *Form → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * CTA Button field in *Form → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.cta_button
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_button: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Form*
 */
type FormSliceVariation = FormSliceDefault;

/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: Form
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FormSlice = prismic.SharedSlice<"form", FormSliceVariation>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Heading field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Description field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Date field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.date
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  date: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Time field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  time: prismic.KeyTextField;

  /**
   * Location field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.location
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  location: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Item in *Participants → Default → Primary → Companies*
 */
export interface PartnersSliceDefaultPrimaryCompaniesItem {
  /**
   * Logo field in *Participants → Default → Primary → Companies*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.companies[].logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Primary content in *Participants → Default → Primary*
 */
export interface PartnersSliceDefaultPrimary {
  /**
   * Companies field in *Participants → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: partners.default.primary.companies[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  companies: prismic.GroupField<
    Simplify<PartnersSliceDefaultPrimaryCompaniesItem>
  >;
}

/**
 * Default variation for Participants Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PartnersSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Participants*
 */
type PartnersSliceVariation = PartnersSliceDefault;

/**
 * Participants Shared Slice
 *
 * - **API ID**: `partners`
 * - **Description**: Partners
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnersSlice = prismic.SharedSlice<
  "partners",
  PartnersSliceVariation
>;

/**
 * Item in *SectorsRepresented → Default → Primary → Marquee*
 */
export interface SectorsRepresentedSliceDefaultPrimaryMarqueeItem {
  /**
   * Partners field in *SectorsRepresented → Default → Primary → Marquee*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sectors_represented.default.primary.marquee[].partners
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  partners: prismic.KeyTextField;
}

/**
 * Primary content in *SectorsRepresented → Default → Primary*
 */
export interface SectorsRepresentedSliceDefaultPrimary {
  /**
   * Heading field in *SectorsRepresented → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sectors_represented.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Marquee field in *SectorsRepresented → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: sectors_represented.default.primary.marquee[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  marquee: prismic.GroupField<
    Simplify<SectorsRepresentedSliceDefaultPrimaryMarqueeItem>
  >;
}

/**
 * Default variation for SectorsRepresented Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectorsRepresentedSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SectorsRepresentedSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *SectorsRepresented*
 */
type SectorsRepresentedSliceVariation = SectorsRepresentedSliceDefault;

/**
 * SectorsRepresented Shared Slice
 *
 * - **API ID**: `sectors_represented`
 * - **Description**: SectorsRepresented
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SectorsRepresentedSlice = prismic.SharedSlice<
  "sectors_represented",
  SectorsRepresentedSliceVariation
>;

/**
 * Item in *SpeakersOfBangaloreEdition → Default → Primary → Speaker*
 */
export interface SpeakersOfBangaloreEditionSliceDefaultPrimarySpeakerItem {
  /**
   * Speaker Image field in *SpeakersOfBangaloreEdition → Default → Primary → Speaker*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.speaker[].speaker_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  speaker_image: prismic.ImageField<never>;

  /**
   * Name field in *SpeakersOfBangaloreEdition → Default → Primary → Speaker*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.speaker[].name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Role field in *SpeakersOfBangaloreEdition → Default → Primary → Speaker*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.speaker[].role
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  role: prismic.KeyTextField;

  /**
   * LinkedIn field in *SpeakersOfBangaloreEdition → Default → Primary → Speaker*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.speaker[].linkedin
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  linkedin: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *SpeakersOfBangaloreEdition → Default → Primary*
 */
export interface SpeakersOfBangaloreEditionSliceDefaultPrimary {
  /**
   * Heading field in *SpeakersOfBangaloreEdition → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Speaker field in *SpeakersOfBangaloreEdition → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: speakers_of_bangalore_edition.default.primary.speaker[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  speaker: prismic.GroupField<
    Simplify<SpeakersOfBangaloreEditionSliceDefaultPrimarySpeakerItem>
  >;
}

/**
 * Default variation for SpeakersOfBangaloreEdition Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpeakersOfBangaloreEditionSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<SpeakersOfBangaloreEditionSliceDefaultPrimary>,
    never
  >;

/**
 * Slice variation for *SpeakersOfBangaloreEdition*
 */
type SpeakersOfBangaloreEditionSliceVariation =
  SpeakersOfBangaloreEditionSliceDefault;

/**
 * SpeakersOfBangaloreEdition Shared Slice
 *
 * - **API ID**: `speakers_of_bangalore_edition`
 * - **Description**: SpeakersOfBangaloreEdition
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SpeakersOfBangaloreEditionSlice = prismic.SharedSlice<
  "speakers_of_bangalore_edition",
  SpeakersOfBangaloreEditionSliceVariation
>;

/**
 * Item in *WhatYouTakeAway → Default → Primary → Blocks*
 */
export interface WhatYouTakeAwaySliceDefaultPrimaryBlocksItem {}

/**
 * Primary content in *WhatYouTakeAway → Default → Primary*
 */
export interface WhatYouTakeAwaySliceDefaultPrimary {
  /**
   * Heading field in *WhatYouTakeAway → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: what_you_take_away.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Blocks field in *WhatYouTakeAway → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: what_you_take_away.default.primary.blocks[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  blocks: prismic.GroupField<
    Simplify<WhatYouTakeAwaySliceDefaultPrimaryBlocksItem>
  >;
}

/**
 * Default variation for WhatYouTakeAway Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhatYouTakeAwaySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhatYouTakeAwaySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhatYouTakeAway*
 */
type WhatYouTakeAwaySliceVariation = WhatYouTakeAwaySliceDefault;

/**
 * WhatYouTakeAway Shared Slice
 *
 * - **API ID**: `what_you_take_away`
 * - **Description**: WhatYouTakeAway
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhatYouTakeAwaySlice = prismic.SharedSlice<
  "what_you_take_away",
  WhatYouTakeAwaySliceVariation
>;

/**
 * Item in *WhosInTheRoom → Default → Primary → Info group*
 */
export interface WhosInTheRoomSliceDefaultPrimaryInfoGroupItem {
  /**
   * Info field in *WhosInTheRoom → Default → Primary → Info group*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whos_in_the_room.default.primary.info_group[].info
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  info: prismic.KeyTextField;
}

/**
 * Primary content in *WhosInTheRoom → Default → Primary*
 */
export interface WhosInTheRoomSliceDefaultPrimary {
  /**
   * Info group field in *WhosInTheRoom → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: whos_in_the_room.default.primary.info_group[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  info_group: prismic.GroupField<
    Simplify<WhosInTheRoomSliceDefaultPrimaryInfoGroupItem>
  >;
}

/**
 * Default variation for WhosInTheRoom Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhosInTheRoomSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhosInTheRoomSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhosInTheRoom*
 */
type WhosInTheRoomSliceVariation = WhosInTheRoomSliceDefault;

/**
 * WhosInTheRoom Shared Slice
 *
 * - **API ID**: `whos_in_the_room`
 * - **Description**: WhosInTheRoom
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhosInTheRoomSlice = prismic.SharedSlice<
  "whos_in_the_room",
  WhosInTheRoomSliceVariation
>;

/**
 * Primary content in *WhyThisEvent → Default → Primary*
 */
export interface WhyThisEventSliceDefaultPrimary {
  /**
   * Heading field in *WhyThisEvent → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: why_this_event.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;
}

/**
 * Default variation for WhyThisEvent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhyThisEventSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhyThisEventSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhyThisEvent*
 */
type WhyThisEventSliceVariation = WhyThisEventSliceDefault;

/**
 * WhyThisEvent Shared Slice
 *
 * - **API ID**: `why_this_event`
 * - **Description**: WhyThisEvent
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WhyThisEventSlice = prismic.SharedSlice<
  "why_this_event",
  WhyThisEventSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AgendaSlice,
      AgendaSliceDefaultPrimaryBlocksItem,
      AgendaSliceDefaultPrimary,
      AgendaSliceVariation,
      AgendaSliceDefault,
      FormSlice,
      FormSliceDefaultPrimary,
      FormSliceVariation,
      FormSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      PartnersSlice,
      PartnersSliceDefaultPrimaryCompaniesItem,
      PartnersSliceDefaultPrimary,
      PartnersSliceVariation,
      PartnersSliceDefault,
      SectorsRepresentedSlice,
      SectorsRepresentedSliceDefaultPrimaryMarqueeItem,
      SectorsRepresentedSliceDefaultPrimary,
      SectorsRepresentedSliceVariation,
      SectorsRepresentedSliceDefault,
      SpeakersOfBangaloreEditionSlice,
      SpeakersOfBangaloreEditionSliceDefaultPrimarySpeakerItem,
      SpeakersOfBangaloreEditionSliceDefaultPrimary,
      SpeakersOfBangaloreEditionSliceVariation,
      SpeakersOfBangaloreEditionSliceDefault,
      WhatYouTakeAwaySlice,
      WhatYouTakeAwaySliceDefaultPrimaryBlocksItem,
      WhatYouTakeAwaySliceDefaultPrimary,
      WhatYouTakeAwaySliceVariation,
      WhatYouTakeAwaySliceDefault,
      WhosInTheRoomSlice,
      WhosInTheRoomSliceDefaultPrimaryInfoGroupItem,
      WhosInTheRoomSliceDefaultPrimary,
      WhosInTheRoomSliceVariation,
      WhosInTheRoomSliceDefault,
      WhyThisEventSlice,
      WhyThisEventSliceDefaultPrimary,
      WhyThisEventSliceVariation,
      WhyThisEventSliceDefault,
    };
  }
}
